import { Accordion, AccordionSummary, AccordionDetails, Typography } from "@mui/material";
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

export default function FAQs() {
  return (
    <div>
      <Accordion>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography>What is the purpose of this dashboard?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            This dashboard is designed to help monitor sales and revenue generated by various menu items.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography>How is the data gathered?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            The data is sourced from the restaurant's point-of-sale systems and other data sources.
          </Typography>
        </AccordionDetails>
      </Accordion>
    </div>
  );
}